### ISSUE TITLE
Simple Example

### ISSUE THREAD

**Issue by harryhaaren** [x42/robtk#4]
Hey, I've looked at using RobTK for simple UIs a few times. Having a simple example would make it easier - any chance you want to add one for RobTK noobs like me? :D

**Comment by x42** [comment]
The problem is: it's isn't simple :(    It grew from some _gtk drop-in-replacement_ to a pragmatic mess.

A simple UI for a standalone app?  https://github.com/x42/scarlett-mixer that might actually be the least fancy UI, I've yet done with robtk.

I suppose I could whip up a single-knob eg-amp.lv2 UI. I'll put it on the ToDo list for a long winter night.

**Comment by harryhaaren** [comment]
Yeah I gathered it wasn't super easy - i did have a quick attempt at hacking the source. Indeed it was the scarlett-mixer post that reminded me had intentions to dig into robtk sometime. Leave it with me for a week or two and I'll report back :)

**Comment by harryhaaren** [comment]
Just to follow up on this - given the "tie in" with LV2, and the (as noted above) "pragmatic mess", I'm not pursuing usage of RobTK for simple standalone applications, as it doesn't fit the requirements (its very close, but just not). Marking closed!
